### ISSUE TITLE
Upgrade mongoose version from 4 to 5

### ISSUE THREAD

**Issue by kevinlmadison** [stennettm/historical#11]
Hey,

I'm wondering if it would be possible to go ahead and upgrade the mongoose version for this lib to version 5+? One of our projects recently went through an upgrade to version 5 and we thought it might be worth investigating upgrading this lib as well. Please let me know what you think. 

I referenced [this document](https://github.com/Automattic/mongoose/blob/master/migrating_to_5.md) for making changes to our codebase.

Thanks

Kevin

**Comment by stennettm** [comment]
Yes, lets do this.

**Comment by kevinlmadison** [comment]
Hey @stennettm I see your merge relating to this issue and I was wondering if your plan was to create a new release with those few tests still failing? I apologize if you're already working on this.

**Comment by stennettm** [comment]
@kevinlmadison I've removed testing on some older versions of node, my reasoning being that if mongoose no longer supports older node versions there's no reason for this plugin to test on them, so no worries there.

Now I am making sure I am happy with the tests and their coverage of the new features we've added, and I'll cut a new release soon.

**Comment by kevinlmadison** [comment]
@stennettm Awesome! I'll keep an eye out for when that goes out, thanks!

**Comment by stennettm** [comment]
Thanks again for your help, this was released under v2.0.0
