### ISSUE TITLE
Update on project stability

### ISSUE THREAD

**Issue by dpasqualin** [stennettm/historical#3]
Hello, I find your plugin rather interesting and I was wondering what do you mean by saying that it should be considered unstable. Is there any known bug? Thanks.

**Comment by stennettm** [comment]
At this stage in development the package is very much 'use at your own risk' since I haven't tested it thoroughly enough to warrant a production release. That being said, there are no known bugs at this time.

**Comment by dpasqualin** [comment]
Ok, we will perform some tests here and come back to you if we find any problems. If you have a TODO list in mind please add it in the repository and we'll try to find some time to help you with the development.

**Comment by stennettm** [comment]
I appreciate it, thanks.
