### ISSUE TITLE
Defaults missing

### ISSUE THREAD

**Issue by orechova** [stennettm/historical#4]
Hi,
we've run to this problem:

Schema contains some fields with default values
When new mongoose model is created, it has these default fields.
On save, these fields are not contained in the initial history document.

example:

`var mySchema = mongoose.Schema({

  name: String,
  status: {
    type: String,
    default: 'start'
  }
});
mySchema.plugin(require('historical'), ...`

`var newThing = myModel({ name : 'xxx' });
newThing.save(); `

And created historical document, missing the status: 'start' field:

`{
    "_id" : ObjectId("12345"),
    "document" : ObjectId("123"),
    "diff" : {
        "name" : "xxx"
    },
    "timestamp" : ISODate("2016-10-18T13:35:24.458Z"),
    "__v" : 0
}`

When using historicalRestore, these default fields are missing until they are changed.

Could you add support for this? 

Thank you very much

**Comment by stennettm** [comment]
Thank you for bringing this to my attention! I will have this fixed soon.

**Comment by stennettm** [comment]
I have addressed this issue with release v1.0.1, thanks again.

**Comment by orechova** [comment]
works great, thank you
