### ISSUE TITLE
Add functionality for FindOneAndUpdate ?

### ISSUE THREAD

**Issue by smudgester** [stennettm/historical#5]
Hi,

I have recently discovered your plugin and in most areas it does exactly what I want.

However, is there any chance it can be updated so that a historical is added when I do a FindOneAndUpdate or FindByIdAndUpdate on my model ?

At the moment I am having to do a model.find() ... if (doc) then { update } else { save } which, whilst it works is not as clean as FindOneAndUpdate.

**Comment by stennettm** [comment]
Thanks for the feature request!

However, unfortunately this is by design as mongoose does not support pre and post middleware for those functions. http://mongoosejs.com/docs/middleware.html#notes

**Comment by stennettm** [comment]
An update: This functionality is now available in mongoose, issue #6 is the related enhancement for this work.
