### ISSUE TITLE
enhancement: provide more middleware hooks

### ISSUE THREAD

**Issue by marcelh-gh** [stennettm/historical#6]
Mongoose supports middleware for these functions now:

- `findOneAndRemove`
- `findOneAndUpdate`
- `update` 

So far _historical_ is only hooked to `save`.

**Comment by stennettm** [comment]
Thank you for the heads up, I'll update the project.

**Comment by kevinlmadison** [comment]
Hello, 
Just want to check on the status of this update? I don't see a PR but if there is already work that's been done I'd rather contribute to that then start from scratch.

Thank You

**Comment by stennettm** [comment]
Kevin,

Thanks for the question. There hasn't been work towards this yet, but I am planning on getting to it soon. If you have any ideas in the meantime I would be happy to look at a PR.

**Comment by kevinlmadison** [comment]
@stennettm Are you open to a Work In Progress PR? I have something along the lines of what I think could work but I'm having some trouble with it. I know the pre findOneAndUpdate hook works on the backend so we have to approach this differently than pre save but I think I might be missing something about how your code is working.

**Comment by stennettm** [comment]
@kevinlmadison Sure, go ahead!

**Comment by kevinlmadison** [comment]
Hi @stennettm I still plan on working on this, didn't mean to leave you hanging on my last PR. Just wanted to let you know. Thanks

**Comment by stennettm** [comment]
No worries Kevin! I've made a few adjustments. I believe we're in a good place with the code, we just need passing tests now.

**Comment by stennettm** [comment]
Released under v2.0.0
